version: "3.7"
services:
  backend:
    build: ./backend
    volumes:
    - "./volumes/data.db:/home/app/prisma/data.db"

  frontend:
    depends_on:
      - backend
    build: ./frontend

  nginx:
    depends_on:
      - backend
      - frontend
    build: ./nginx
    volumes:
      - "/etc/letsencrypt/live/dev.jakubsekula.com/fullchain.pem:/etc/nginx/certificates/fullchain.pem"
      - "/etc/letsencrypt/live/dev.jakubsekula.com/privkey.pem:/etc/nginx/certificates/privkey.pem"
    ports:
      - "80:80"
      - "443:443"
