version: "3.7"
services:
  habits-backend:
    build: ./backend
    volumes:
      - "./volumes/data.db:/home/app/prisma/data.db"
    ports:
      - "3000:3000"
    networks:
      - deployment-server_jakubsekula-network

  habits-frontend:
    depends_on:
      - habits-backend
    build: ./frontend
    ports:
      - "3001:3001"
    networks:
      - deployment-server_jakubsekula-network

networks:
  deployment-server_jakubsekula-network:
    external: true